services:
  bot:
    image: "anonflow:${VERSION}"
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      version: "${VERSION}"
      description: "Telegram-бот для анонимных сообщений"
    volumes:
      - ./rules/:/app/rules/
      - ./config.yml:/app/config.yml
