services:
  bot:
    image: "anonflow"
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      version: "${VERSION}"
    volumes:
      - ./rules/:/app/rules/
      - ./config.yml:/app/config.yml
